/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.schneezey.pojo;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SmallPojo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8585375321529568441L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SmallPojo\",\"namespace\":\"io.schneezey.pojo\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"testString\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SmallPojo> ENCODER =
      new BinaryMessageEncoder<SmallPojo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SmallPojo> DECODER =
      new BinaryMessageDecoder<SmallPojo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SmallPojo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SmallPojo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SmallPojo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SmallPojo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SmallPojo from a ByteBuffer. */
  public static SmallPojo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int id;
   private java.lang.CharSequence testString;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SmallPojo() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param testString The new value for testString
   */
  public SmallPojo(java.lang.Integer id, java.lang.CharSequence testString) {
    this.id = id;
    this.testString = testString;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return testString;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: testString = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'testString' field.
   * @return The value of the 'testString' field.
   */
  public java.lang.CharSequence getTestString() {
    return testString;
  }

  /**
   * Sets the value of the 'testString' field.
   * @param value the value to set.
   */
  public void setTestString(java.lang.CharSequence value) {
    this.testString = value;
  }

  /**
   * Creates a new SmallPojo RecordBuilder.
   * @return A new SmallPojo RecordBuilder
   */
  public static io.schneezey.pojo.SmallPojo.Builder newBuilder() {
    return new io.schneezey.pojo.SmallPojo.Builder();
  }

  /**
   * Creates a new SmallPojo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SmallPojo RecordBuilder
   */
  public static io.schneezey.pojo.SmallPojo.Builder newBuilder(io.schneezey.pojo.SmallPojo.Builder other) {
    return new io.schneezey.pojo.SmallPojo.Builder(other);
  }

  /**
   * Creates a new SmallPojo RecordBuilder by copying an existing SmallPojo instance.
   * @param other The existing instance to copy.
   * @return A new SmallPojo RecordBuilder
   */
  public static io.schneezey.pojo.SmallPojo.Builder newBuilder(io.schneezey.pojo.SmallPojo other) {
    return new io.schneezey.pojo.SmallPojo.Builder(other);
  }

  /**
   * RecordBuilder for SmallPojo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SmallPojo>
    implements org.apache.avro.data.RecordBuilder<SmallPojo> {

    private int id;
    private java.lang.CharSequence testString;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.schneezey.pojo.SmallPojo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.testString)) {
        this.testString = data().deepCopy(fields()[1].schema(), other.testString);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SmallPojo instance
     * @param other The existing instance to copy.
     */
    private Builder(io.schneezey.pojo.SmallPojo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.testString)) {
        this.testString = data().deepCopy(fields()[1].schema(), other.testString);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.schneezey.pojo.SmallPojo.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.schneezey.pojo.SmallPojo.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'testString' field.
      * @return The value.
      */
    public java.lang.CharSequence getTestString() {
      return testString;
    }

    /**
      * Sets the value of the 'testString' field.
      * @param value The value of 'testString'.
      * @return This builder.
      */
    public io.schneezey.pojo.SmallPojo.Builder setTestString(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.testString = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'testString' field has been set.
      * @return True if the 'testString' field has been set, false otherwise.
      */
    public boolean hasTestString() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'testString' field.
      * @return This builder.
      */
    public io.schneezey.pojo.SmallPojo.Builder clearTestString() {
      testString = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SmallPojo build() {
      try {
        SmallPojo record = new SmallPojo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.testString = fieldSetFlags()[1] ? this.testString : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SmallPojo>
    WRITER$ = (org.apache.avro.io.DatumWriter<SmallPojo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SmallPojo>
    READER$ = (org.apache.avro.io.DatumReader<SmallPojo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
